@baseUrl = http://localhost:3000/api
@resourceName = categories

# Categories

# @name getAll
GET {{baseUrl}}/{{resourceName}}

####

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
 "name": ""
}

###

# @name update
PATCH  {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
 "title": ""
}

###

# @name delete
DELETE   {{baseUrl}}/{{resourceName}}/2
