@baseUrl = http://localhost:3000/api
@resourceName = products

# Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?price=114

###

# @name search
GET {{baseUrl}}/{{resourceName}}?name_like=hand

###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=5
 
###

# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

###


# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
 "name": ""
}

###

# @name update
PATCH  {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
 "title": ""
}

###

# @name delete
DELETE   {{baseUrl}}/{{resourceName}}/2
